### ISSUE TITLE
Darwinia balance precise migration checklist(In case we will do it)

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/research#25]
- [ ] Check read and mute entry points
- [ ] Ethereum bridge precision conversion

I would suggest modify the event in substrate side to avoid fork of smart contract in darwinia side.

https://github.com/darwinia-network/darwinia-common/blob/ca11138c82c9bf9c12832fe3cc3ed8ae99b85bbf/frame/wormhole/backing/ethereum/src/lib.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L361

https://github.com/darwinia-network/darwinia-bridge-sol/blob/b2f8940fbb1caba6ce9b38fa90d8083dfc05b060/contracts/deprecated/issuing-backing/contracts/ethereum/TokenIssuing.sol#L115

- [ ] Substrate to substrate bridge and maybe xRING contract decimal?
- [ ] subql and wormhole-backend?
- [ ] wormhole ui?
- [ ] Smart app
- [ ] Apps and Polkadot.js
- [ ] CEX?

**Comment by HackFisher** [comment]
- [ ] Staking Ledger and the other pallets which stores `Balance` related data.
